language: php

php:
  # using major version aliases

  # aliased to 5.2.17
  - 5.2
  # aliased to 5.3.29
  - 5.3
  # aliased to a recent 5.4.x version
  - 5.4
 
env:
  - DB=mysql
  
before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi


script: phpunit --configuration phpunit_$DB.xml --coverage-text